"""
This type stub file was generated by pyright.
"""

from apscheduler.triggers.base import BaseTrigger

class DateTrigger(BaseTrigger):
    """
    Triggers once on the given datetime. If ``run_date`` is left empty, current time is used.

    :param datetime|str run_date: the date/time to run the job at
    :param datetime.tzinfo|str timezone: time zone for ``run_date`` if it doesn't have one already
    """
    __slots__ = ...
    def __init__(self, run_date=..., timezone=...) -> None:
        ...
    
    def get_next_fire_time(self, previous_fire_time, now): # -> datetime | None:
        ...
    
    def __getstate__(self): # -> dict[str, Any]:
        ...
    
    def __setstate__(self, state): # -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self): # -> str:
        ...
    


